# Generated by Django 5.2.2 on 2026-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mensagem_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilePic/'),
        ),
    ]
